import type { Invoice } from './types';
import { escapeHtml } from './escapeHtml';

export function exportInvoicePDF(inv: Invoice, clientName: string) {
  const statusColor = inv.status === 'paid' ? '#10b981' : '#f59e0b';
  const statusLabel = inv.status === 'paid' ? 'PAID' : 'UNPAID';
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"/>
<title>Invoice ${escapeHtml(inv.id)} — ChessDesk</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #1a1a2e; padding: 48px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; border-bottom: 2px solid #7c3aed; padding-bottom: 24px; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand-name { font-size: 22px; font-weight: 700; color: #7c3aed; }
  .brand-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .invoice-meta { text-align: right; }
  .invoice-id { font-size: 20px; font-weight: 700; color: #1a1a2e; }
  .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; letter-spacing: 0.05em; background: ${statusColor}22; color: ${statusColor}; border: 1px solid ${statusColor}; margin-top: 6px; }
  .section { margin-bottom: 28px; }
  .section-title { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af; margin-bottom: 8px; }
  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
  .field-label { font-size: 11px; color: #9ca3af; margin-bottom: 2px; }
  .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
  .amount-box { background: #f3f0ff; border: 1px solid #ddd6fe; border-radius: 12px; padding: 20px 24px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 28px; }
  .amount-label { font-size: 13px; color: #6b7280; }
  .amount-value { font-size: 28px; font-weight: 700; color: #7c3aed; }
  .notes-box { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px 16px; font-size: 13px; color: #4b5563; line-height: 1.6; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
  @media print { body { padding: 32px; } }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">
      <div>
        <div class="brand-name">♝ ChessDesk</div>
        <div class="brand-sub">Run your chess coaching business from one place.</div>
      </div>
    </div>
    <div class="invoice-meta">
      <div class="invoice-id">Invoice #${escapeHtml(inv.id)}</div>
      <div class="status-badge">${statusLabel}</div>
    </div>
  </div>

  <div class="section grid-2">
    <div>
      <div class="section-title">Billed To</div>
      <div class="field-value">${escapeHtml(clientName)}</div>
    </div>
    <div>
      <div class="section-title">Dates</div>
      <div class="field-label">Invoice Date</div>
      <div class="field-value">${escapeHtml(inv.invoice_date)}</div>
      <div class="field-label" style="margin-top:8px">Due Date</div>
      <div class="field-value">${escapeHtml(inv.due_date)}</div>
      ${inv.paid_date ? `<div class="field-label" style="margin-top:8px">Paid Date</div><div class="field-value" style="color:#10b981">${escapeHtml(inv.paid_date)}</div>` : ''}
    </div>
  </div>

  ${inv.description ? `<div class="section">
    <div class="section-title">Description</div>
    <div class="field-value">${escapeHtml(inv.description)}</div>
  </div>` : ''}

  <div class="amount-box">
    <div class="amount-label">Total Amount Due</div>
    <div class="amount-value">R ${inv.amount.toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
  </div>

  ${inv.notes ? `<div class="section">
    <div class="section-title">Notes</div>
    <div class="notes-box">${escapeHtml(inv.notes)}</div>
  </div>` : ''}

  <div class="footer">Generated by ChessDesk · ${new Date().toLocaleDateString('en-ZA', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.opener = null;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 500);
}
